#!/usr/bin/env sh
set -eu
cook=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $cook/lib/sh.sh


if [ $# -eq 0 ]; then
    set -- build
fi


for action in $@ ; do
    test -f $cook/actions/$action || die "Don't know how to $action"
done


cook_normal() {
    for action in $@ ; do
        $cook/actions/$action
    done
}


cook_workspace() {
    for dir in $(lsdirs) ; do
        test -d $dir/.git || continue
        cd $dir

        heading "$dir/"
        echo_on
        $cook/cook $@
        echo_off

        cd $OLDPWD
    done
}


if [ ! -d .git ] && ls */.git &> /dev/null ; then
    cook_workspace $@
else
    cook_normal $@
fi
