#!/usr/bin/env sh
set -eu
cook=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $cook/lib/sh.sh


if [ $# -eq 0 ]; then
    set -- build
fi


for action in $@ ; do
    test -f $cook/actions/$action || die "Don't know how to $action"
done


for action in $@ ; do
    $cook/actions/$action
done
