#!/usr/bin/env sh
set -eu
cook=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)


. $cook/lib/sh.sh


action=${1:-build}
test -f $cook/actions/$action || die "Don't know how to $action"


$cook/actions/$action

