#!/usr/bin/env sh
set -eu
cook=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


detects="$(ls $cook/types/detect-[0-9][0-9][0-9]-* 2> /dev/null | sort -r)"
for detect in $detects ; do
    type="${detect##*/}"
    type="${type#detect-}"
    type="${type#[0-9][0-9][0-9]-}"
    echo $type
done

