#!/usr/bin/env sh
set -eu
cook=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


. $cook/lib/sh.sh


user=$(current_user)
uid=$(current_uid)
gid=$(current_gid)


heading "Building cook-dotnet-sdk container"

$cook/lib/build-container \
    $cook/lib/cook-dotnet-sdk.Dockerfile \
    cook-dotnet-sdk \
    --label cook \
    --build-arg user=$user \
    --build-arg uid=$uid \
    --build-arg gid=$gid
