#!/usr/bin/env sh
set -eu
cook=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


type="$($cook/lib/detect-type)"
test -n "$type" || exit


action="restore"
test -f $cook/actions/$action-$type || exit
$cook/actions/$action-$type
