#!/usr/bin/env sh
set -eu
cook=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


. $cook/lib/sh.sh


action="restore"
type="dotnet-sln"


hostdir="$(pwd)"
hostdirname="${hostdir##*/}"


echo_on
hotbox \
    alpine-dotnet-builder build-$hostdirname \
    -- \
    /cook/actions/$action-$type
echo_off
