#!/usr/bin/env sh
set -eu
cook=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


default_hotbox="alpine-dotnet-builder"
custom_hotbox_patterns="*-restorer *-builder"
action="restore-dotnet-sln"
. $cook/actions/_hotbox.sh
