#!/usr/bin/env sh
set -eu
cook=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)


. $cook/lib/sh.sh


hostdir="$(pwd)"
hostdirname="${hostdir##*/}"


echo_on
hotbox \
    alpine-dotnet-builder test-$hostdirname \
    -- \
    /cook/actions/test-dotnet-sln
echo_off
